export default {
  GET_APPOINTMENT: 'GET_APPOINTMENT',
  CONFIRM_APPOINTMENT: 'CONFIRM_APPOINTMENT',
  CANCEL_APPOINTMENT: 'CANCEL_APPOINTMENT',
  SCHEDULE_APPOINTMENT: 'SCHEDULE_APPOINTMENT',
  SET_WEEKLY_SLOTS: 'SET_WEEKLY_SLOTS',
  CLEAR_WEEKLY_SLOTS: 'CLEAR_WEEKLY_SLOTS',
};
